version: '3'
services:
  web:
    image: verbral/docker-drupal:8.1-v4-apache-node16
    ports:
      - 80:80
    environment:
      APACHE_DOCUMENT_ROOT: web
      PHP_EXTENSION_GD: 1
      DRUPAL_CORE_CONSTRAINT: 9.4.x-dev
      DRUSH_DRUSH_CONSTRAINT: ^10
      PHP_EXTENSION_XDEBUG: 1
      XDEBUG_MODE: debug
      XDEBUG_SESSION: 1
      XDEBUG_CLIENT_HOST: 127.0.0.1
      SIMPLETEST_DB: mysql://root:@mysql/db
      SIMPLETEST_BASE_URL: http://web
      BROWSERTEST_OUTPUT_DIRECTORY: /var/www/html/web/sites/simpletest/browser_output
      MINK_DRIVER_CLASS: \Drupal\FunctionalJavascriptTests\DrupalSelenium2Driver
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome",{"browserName":"chrome","chromeOptions":{"w3c":false,"args":["--allowed-ips=", "--allowed-origins=*", "--disable-dev-shm-usage"]}}, "http://chrome:4444/wd/hub"]'
      GRUMPHP_BIN_DIR: /home/docker/.composer/vendor/bin
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/home/docker/.ssh
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    volumes:
      - mysql:/var/lib/mysql
  chrome:
    image: selenium/standalone-chrome
    ports:
      - 7900:7900
volumes:
  mysql:
