version: '3'
services:
  web:
    image: verbral/docker-drupal:8.1-v4-apache
    ports:
      - 80:80
    environment:
      APACHE_DOCUMENT_ROOT: web
      PHP_EXTENSION_GD: 1
      PHP_INI_MEMORY_LIMIT: 1g
    volumes:
      - ${PWD}:/var/www/html
      - ~/.ssh:/home/docker/.ssh
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
